name: Periodic pipeline

on:
#   schedule:
#     - cron: '2 * * * *'
  push:
    branches: [main]

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Ping the deployed service's URL
      uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
      with:
        url: https://full-stack-open-pokedex-proud-haze-1316.fly.dev
        max-attempts: 3
        retry-delay: 5s
