name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]    

env:
  PR_CHECK: ${{ github.event_name == 'pull_request' }}
  SKIP_CHECK: ${{ contains(join(github.event.commits.*.message), '#skip deploy') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
      
      - name: lint #linting
        run: npm run eslint
      
      - name: build #building
        run: npm run build
      
      - name: test (Jest) #unit testing
        run: npm run test

      - name: e2e tests (Cypress) #e2e testing
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000  

      - name: Setup Flyctl #setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io #fly.io deployment
        if: ${{ !env.PR_CHECK && !env.SKIP_CHECK }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Trigger deployment #render deployment
        if: ${{ !env.PR_CHECK && !env.SKIP_CHECK }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ !github.env.PR_CHECK  }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch